//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO.SGP.EntidadesDeNegocio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class webpages_Roles
    {
        public webpages_Roles()
        {
            this.Usuarios = new HashSet<Usuarios>();
            this.Menus = new HashSet<Menus>();
        }

        [Key]
        public int RoleId { get; set; }

        public string RoleName { get; set; }

        public string ItemMenuDefault { get; set; }

        public virtual ICollection<Usuarios> Usuarios { get; set; }
        public virtual ICollection<Menus> Menus { get; set; }
    }
}
