using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

/// <summary>
///  CODE GENERATED BY Xeus Technology 
///  Date: 21/04/2016 10:53:37
///  Version: 3
/// <summary>

namespace SSO.SGP.EntidadesDeNegocio.Vistas
{
    public class RolesItemsMenuView
    {
        #region Propiedades

        [Display(Name = "Rol_Id", Order = 50)]
        public int Rol_Id { get; set; }

        [Display(Name = "Men_id", Order = 50)]
        public int Men_id { get; set; }


        #endregion


    }
}
