using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

/// <summary>
///  CODE GENERATED BY Xeus Technology 
///  Date: 17/07/2016 17:47:35
///  Version: 3
/// <summary>

namespace SSO.SGP.EntidadesDeNegocio.Vistas
{
    public class webpages_RolesView
    {
        #region Propiedades

        [Display(Name = "Id", Order = 11)]
        public int Id { get; set; }

        [Display(Name = "Rol", Order = 50)]
        public string RoleName { get; set; }

        //[Display(Name = "Menu Inicial", Order = 40)]
        //public string MenuIcial { get; set; }


        #endregion


    }
}
