using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSO.SGP.EntidadesDeNegocio;
using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
using SSO.SGP.AccesoADatos;
using SSO.SGP.EntidadesDeNegocio.Vistas;
using System;
using System.Data;
using System.Collections.Generic;
using System.IO;
using Syncrosoft.Framework.Utils.Logs;

/// <summary>
///  CODE GENERATED BY Xeus Technology 
///  Date: 13/12/2018 7:26:17
///  Version: 3
/// <summary>
namespace SSO.SGP.Web.Areas.Expedientes.Controllers
{
    public class MontosDeViaticosController : Controller
    {
        private MontosDeViaticosAD oMontosDeViaticos = new MontosDeViaticosAD();
        private LocalidadesRefAD oLocalidades = new LocalidadesRefAD();

        #region Views

        public ActionResult Default()
        {
            return View();
        }

        public ActionResult Index()
        {
            var m = new MontosDeViaticos();
            return View(m);
        }
        public ActionResult Crear()
        {
            var m = new MontosDeViaticos();
            return View(m);
        }

        public ActionResult Editar(int id = 0)
        {

            MontosDeViaticos montosdeviaticos = oMontosDeViaticos.ObtenerPorId(id);
            if (montosdeviaticos == null)
            {
                return HttpNotFound();
            }
            return View(montosdeviaticos);
        }

        #endregion

        #region HttpPost

        [HttpPost]
        public ActionResult Crear(MontosDeViaticos montosdeviaticos)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    oMontosDeViaticos.Guardar(montosdeviaticos);
                    return Json(new object[] { true, String.Format("Operación satisfactoria"), montosdeviaticos.Id });
                }
                catch (Exception ex)
                {
                    Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido procesar la operación" });
                }
            }
            else
            {
                return Json(new object[] { false, "Ha ocurrido un error en la validación" });
            }
        }

        [HttpPost]
        public ActionResult Editar(MontosDeViaticos montosdeviaticos)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    oMontosDeViaticos.Actualizar(montosdeviaticos);
                    return Json(new object[] { true, String.Format("Operación satisfactoria") });
                }
                catch (Exception ex)
                {
                    Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido procesar la operación" });
                }
            }
            else
            {
                return Json(new object[] { false, "Ha ocurrido un error en la validació" });
            }
        }

        [HttpPost, ActionName("Eliminar")]
        public ActionResult EliminarConfirmado(int id)
        {
            try
            {
                oMontosDeViaticos.Eliminar(id);

                return Json(new object[] { true, "La operación se realizó satisfactoriamente" });
            }
            catch (Exception)
            {
                return Json(new object[] { false, "No pudo eliminarse el elementos" });
            }

        }


        #endregion

        #region JsonResult

        public DataTablesResult<MontosDeViaticosView> getMontosDeViaticosGrid(DataTablesParam dataTableParam)
        {
            return DataTablesResult.Create(this.oMontosDeViaticos.ObtenerParaGrilla(), dataTableParam, x => x);
        }

        public JsonResult Options()
        {
            var res = from x in this.oMontosDeViaticos.ObtenerOptions("")
                      select x;
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }

        //public JsonResult Table(string term)
        //{
        //    var res = from x in this.oMontosDeViaticos.JsonT(term)
        //              select x;
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        public JsonResult GetData(int id)
        {
            return this.Json(this.oMontosDeViaticos.ObtenerPorId(id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult JsonOptionsLocalidades(string term)
        {
            var res = from x in this.oLocalidades.ObtenerOptions(term)
                      select new { id = x.value, label = x.text };
            return this.Json(res, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetVigente()
        {
            return this.Json(this.oMontosDeViaticos.ObtenerVigente(), JsonRequestBehavior.AllowGet);
        }

        //public JsonResult Autocomplete(string term)
        //{
        //    var res = from x in this.oMontosDeViaticos.ObtenerAutocomplete(term)
        //              select new { id = x.Id, label = x.Id.ToString() };
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        //public JsonResult ExecuteQuery(string where_c, string order_c)
        //{
        //    var res = from x in this.oMontosDeViaticos.ExecuteQuery(where_c, order_c, 0, 0)
        //              select x;
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        #endregion

        protected override void Dispose(bool disposing)
        {
            //oMontosDeViaticos.Dispose();

            base.Dispose(disposing);
        }


    }
}
