using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSO.SGP.EntidadesDeNegocio;
using Syncrosoft.Framework.Controles.Mvc.JQuery.Datatables;
using SSO.SGP.AccesoADatos;
using SSO.SGP.EntidadesDeNegocio.Vistas;
using System;
using System.Data;
using System.Collections.Generic;
using System.IO;
using Syncrosoft.Framework.Utils.Logs;

/// <summary>
///  CODE GENERATED BY Xeus Technology 
///  Date: 13/12/2018 7:26:28
///  Version: 3
/// <summary>
namespace SSO.SGP.Web.Controllers
{
    public class SolicitudesDeViaticosAgentesController : Controller
    {
        private SolicitudesDeViaticosAgentesAD oSolicitudesDeViaticosAgentes = new SolicitudesDeViaticosAgentesAD();
        private SolicitudesDeViaticosAD oSolicitudesDeViaticos = new SolicitudesDeViaticosAD();
        private AgentesAD oAgentes = new AgentesAD();

        #region Views

        public ActionResult Default()
        {
            return View();
        }

        public ActionResult Index()
        {
            var m = new SolicitudesDeViaticosAgentes();
            return View(m);
        }
        public ActionResult Crear()
        {
            var m = new SolicitudesDeViaticosAgentes();
            ViewBag.SolicitudDeViatico = oSolicitudesDeViaticos.ObtenerOptions("").ToList();
            ViewBag.Agente = oAgentes.ObtenerOptions("").ToList();
            return View(m);
        }

        public ActionResult Editar(int id = 0)
        {
            ViewBag.SolicitudDeViatico = oSolicitudesDeViaticos.ObtenerOptions("").ToList();
            ViewBag.Agente = oAgentes.ObtenerOptions("").ToList();

            SolicitudesDeViaticosAgentes solicitudesdeviaticosagentes = oSolicitudesDeViaticosAgentes.ObtenerPorId(id);
            if (solicitudesdeviaticosagentes == null)
            {
                return HttpNotFound();
            }
            return View(solicitudesdeviaticosagentes);
        }

        #endregion

        #region HttpPost

        [HttpPost]
        public ActionResult Crear(SolicitudesDeViaticosAgentes solicitudesdeviaticosagentes)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    oSolicitudesDeViaticosAgentes.Guardar(solicitudesdeviaticosagentes);
                    return Json(new object[] { true, String.Format("Operación satisfactoria"), solicitudesdeviaticosagentes.Id });
                }
                catch (Exception ex)
                {
                    Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido procesar la operación" });
                }
            }
            else
            {
                return Json(new object[] { false, "Ha ocurrido un error en la validación" });
            }
        }

        [HttpPost]
        public ActionResult Editar(SolicitudesDeViaticosAgentes solicitudesdeviaticosagentes)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    oSolicitudesDeViaticosAgentes.Guardar(solicitudesdeviaticosagentes);
                    return Json(new object[] { true, String.Format("Operación satisfactoria") });
                }
                catch (Exception ex)
                {
                    Logger.GrabarExcepcion(ex, false);
                    return Json(new object[] { false, "No se ha podido procesar la operación" });
                }
            }
            else
            {
                return Json(new object[] { false, "Ha ocurrido un error en la validació" });
            }
        }

        [HttpPost, ActionName("Eliminar")]
        public ActionResult EliminarConfirmado(int id)
        {
            try
            {
                oSolicitudesDeViaticosAgentes.Eliminar(id);

                return Json(new object[] { true, "La operación se realizó satisfactoriamente" });
            }
            catch (Exception)
            {
                return Json(new object[] { false, "No pudo eliminarse el elementos" });
            }

        }


        #endregion

        #region JsonResult

        public DataTablesResult<SolicitudesDeViaticosAgentesView> getSolicitudesDeViaticosAgentesGrid(DataTablesParam dataTableParam)
        {
            return DataTablesResult.Create(this.oSolicitudesDeViaticosAgentes.ObtenerParaGrilla(), dataTableParam, x => x);
        }

        //public JsonResult Options()
        //{
        //    var res = from x in this.oSolicitudesDeViaticosAgentes.ObtenerOptions()
        //              select x;
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        //public JsonResult Table(string term)
        //{
        //    var res = from x in this.oSolicitudesDeViaticosAgentes.JsonT(term)
        //              select x;
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        public JsonResult GetData(int id)
        {
            return this.Json(this.oSolicitudesDeViaticosAgentes.ObtenerPorId(id), JsonRequestBehavior.AllowGet);
        }

        //public JsonResult Autocomplete(string term)
        //{
        //    var res = from x in this.oSolicitudesDeViaticosAgentes.ObtenerAutocomplete(term)
        //              select new { id = x.Id, label = x.Id.ToString() };
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        //public JsonResult ExecuteQuery(string where_c, string order_c)
        //{
        //    var res = from x in this.oSolicitudesDeViaticosAgentes.ExecuteQuery(where_c, order_c, 0, 0)
        //              select x;
        //    return this.Json(res, JsonRequestBehavior.AllowGet);
        //}

        #endregion

        protected override void Dispose(bool disposing)
        {
            //oSolicitudesDeViaticosAgentes.Dispose();
            //oSolicitudesDeViaticos.Dispose();
            //oAgentes.Dispose();

            base.Dispose(disposing);
        }


    }
}
