//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSO.SGP.Web.Nucleo_Demo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSConsultaPersonaNSoapBinding", Namespace="Nucleo")]
    public partial class WSConsultaPersonaN : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSConsultaPersonaN() {
            this.Url = global::SSO.SGP.Web.Properties.Settings.Default.SSO_SGP_Web_Nucleo_Demo_WSConsultaPersonaN;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Nucleoaction/AWSCONSULTAPERSONAN.Execute", RequestElementName="WSConsultaPersonaN.Execute", RequestNamespace="Nucleo", ResponseElementName="WSConsultaPersonaN.ExecuteResponse", ResponseNamespace="Nucleo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("Sdtpersonas")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SdtConsultaPersonaSdtConsultaPersonaItem[] Execute(string Personasnnrodoc, string Usuario, string Clave, out short Errornid, out string Errornd) {
            object[] results = this.Invoke("Execute", new object[] {
                        Personasnnrodoc,
                        Usuario,
                        Clave});
            Errornid = ((short)(results[1]));
            Errornd = ((string)(results[2]));
            return ((SdtConsultaPersonaSdtConsultaPersonaItem[])(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(string Personasnnrodoc, string Usuario, string Clave) {
            this.ExecuteAsync(Personasnnrodoc, Usuario, Clave, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(string Personasnnrodoc, string Usuario, string Clave, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        Personasnnrodoc,
                        Usuario,
                        Clave}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SdtConsultaPersona.SdtConsultaPersonaItem", Namespace="Nucleo")]
    public partial class SdtConsultaPersonaSdtConsultaPersonaItem {
        
        private long personasNIdField;
        
        private short documentoNIdField;
        
        private string documentoNDCortaField;
        
        private string personasNNroDocField;
        
        private string personasNDocumentoDefaultField;
        
        private string personasNSexoField;
        
        private string personasNCuilField;
        
        private string personasNApellidoField;
        
        private string personasNApellido2Field;
        
        private string personasNNombreField;
        
        private string personasNNombre2Field;
        
        private string personasNNombre3Field;
        
        private string personasNNombreCompletoField;
        
        private string personasNFechaNacField;
        
        private int localidadNIdField;
        
        private string localidadNDField;
        
        private sbyte personasNFallecidoField;
        
        private string personasNFechaFallField;
        
        private double personasNSintysConfiabilidadField;
        
        private string personasNSintysFechaField;
        
        private long personasNSintysIdField;
        
        private string sTDocumentoNDCortaField;
        
        private string sTDocumentoNDLargaField;
        
        private short sTDocumentoNIdField;
        
        private string sTInstitucionDField;
        
        private int sTInstitucionIdField;
        
        private string sTInsVerificadoraDField;
        
        private int sTInsVerificadoraIdField;
        
        private string sTLocDefuncionNDField;
        
        private int sTLocDefuncionNIdField;
        
        private string personasNenRCCPField;
        
        private string personasNBajaField;
        
        private string personasNFechaBajaField;
        
        /// <comentarios/>
        public long PersonasNId {
            get {
                return this.personasNIdField;
            }
            set {
                this.personasNIdField = value;
            }
        }
        
        /// <comentarios/>
        public short DocumentoNId {
            get {
                return this.documentoNIdField;
            }
            set {
                this.documentoNIdField = value;
            }
        }
        
        /// <comentarios/>
        public string DocumentoNDCorta {
            get {
                return this.documentoNDCortaField;
            }
            set {
                this.documentoNDCortaField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNNroDoc {
            get {
                return this.personasNNroDocField;
            }
            set {
                this.personasNNroDocField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNDocumentoDefault {
            get {
                return this.personasNDocumentoDefaultField;
            }
            set {
                this.personasNDocumentoDefaultField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNSexo {
            get {
                return this.personasNSexoField;
            }
            set {
                this.personasNSexoField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNCuil {
            get {
                return this.personasNCuilField;
            }
            set {
                this.personasNCuilField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNApellido {
            get {
                return this.personasNApellidoField;
            }
            set {
                this.personasNApellidoField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNApellido2 {
            get {
                return this.personasNApellido2Field;
            }
            set {
                this.personasNApellido2Field = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNNombre {
            get {
                return this.personasNNombreField;
            }
            set {
                this.personasNNombreField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNNombre2 {
            get {
                return this.personasNNombre2Field;
            }
            set {
                this.personasNNombre2Field = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNNombre3 {
            get {
                return this.personasNNombre3Field;
            }
            set {
                this.personasNNombre3Field = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNNombreCompleto {
            get {
                return this.personasNNombreCompletoField;
            }
            set {
                this.personasNNombreCompletoField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNFechaNac {
            get {
                return this.personasNFechaNacField;
            }
            set {
                this.personasNFechaNacField = value;
            }
        }
        
        /// <comentarios/>
        public int LocalidadNId {
            get {
                return this.localidadNIdField;
            }
            set {
                this.localidadNIdField = value;
            }
        }
        
        /// <comentarios/>
        public string LocalidadND {
            get {
                return this.localidadNDField;
            }
            set {
                this.localidadNDField = value;
            }
        }
        
        /// <comentarios/>
        public sbyte PersonasNFallecido {
            get {
                return this.personasNFallecidoField;
            }
            set {
                this.personasNFallecidoField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNFechaFall {
            get {
                return this.personasNFechaFallField;
            }
            set {
                this.personasNFechaFallField = value;
            }
        }
        
        /// <comentarios/>
        public double PersonasNSintysConfiabilidad {
            get {
                return this.personasNSintysConfiabilidadField;
            }
            set {
                this.personasNSintysConfiabilidadField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNSintysFecha {
            get {
                return this.personasNSintysFechaField;
            }
            set {
                this.personasNSintysFechaField = value;
            }
        }
        
        /// <comentarios/>
        public long PersonasNSintysId {
            get {
                return this.personasNSintysIdField;
            }
            set {
                this.personasNSintysIdField = value;
            }
        }
        
        /// <comentarios/>
        public string STDocumentoNDCorta {
            get {
                return this.sTDocumentoNDCortaField;
            }
            set {
                this.sTDocumentoNDCortaField = value;
            }
        }
        
        /// <comentarios/>
        public string STDocumentoNDLarga {
            get {
                return this.sTDocumentoNDLargaField;
            }
            set {
                this.sTDocumentoNDLargaField = value;
            }
        }
        
        /// <comentarios/>
        public short STDocumentoNId {
            get {
                return this.sTDocumentoNIdField;
            }
            set {
                this.sTDocumentoNIdField = value;
            }
        }
        
        /// <comentarios/>
        public string STInstitucionD {
            get {
                return this.sTInstitucionDField;
            }
            set {
                this.sTInstitucionDField = value;
            }
        }
        
        /// <comentarios/>
        public int STInstitucionId {
            get {
                return this.sTInstitucionIdField;
            }
            set {
                this.sTInstitucionIdField = value;
            }
        }
        
        /// <comentarios/>
        public string STInsVerificadoraD {
            get {
                return this.sTInsVerificadoraDField;
            }
            set {
                this.sTInsVerificadoraDField = value;
            }
        }
        
        /// <comentarios/>
        public int STInsVerificadoraId {
            get {
                return this.sTInsVerificadoraIdField;
            }
            set {
                this.sTInsVerificadoraIdField = value;
            }
        }
        
        /// <comentarios/>
        public string STLocDefuncionND {
            get {
                return this.sTLocDefuncionNDField;
            }
            set {
                this.sTLocDefuncionNDField = value;
            }
        }
        
        /// <comentarios/>
        public int STLocDefuncionNId {
            get {
                return this.sTLocDefuncionNIdField;
            }
            set {
                this.sTLocDefuncionNIdField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNenRCCP {
            get {
                return this.personasNenRCCPField;
            }
            set {
                this.personasNenRCCPField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNBaja {
            get {
                return this.personasNBajaField;
            }
            set {
                this.personasNBajaField = value;
            }
        }
        
        /// <comentarios/>
        public string PersonasNFechaBaja {
            get {
                return this.personasNFechaBajaField;
            }
            set {
                this.personasNFechaBajaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SdtConsultaPersonaSdtConsultaPersonaItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SdtConsultaPersonaSdtConsultaPersonaItem[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public short Errornid {
            get {
                this.RaiseExceptionIfNecessary();
                return ((short)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Errornd {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591